export interface GuardedBoundaryResult {
  startSec: number;
  endSec: number;
  danglingPronounResolved: boolean;
  cliffhangerResolved: boolean;
  preambleStripped: boolean;
  hallucinationScrubbed: boolean;
  explanation: string;
}

export interface OpeningAnalysisResult {
  hookScore: number;
  isWeakPreamble: boolean;
  thesisStartSec?: number;
  preambleTokens: string[];
  explanation: string;
}

export class ContextCoherenceGuard {
  private readonly danglingPronouns = new Set([
    'he', 'she', 'it', 'they', 'this', 'that', 'these', 'those', 'his', 'her', 'their', 'its'
  ]);

  private readonly trailingConjunctions = new Set([
    'because', 'and', 'or', 'but', 'which', 'so', 'although', 'though', 'since', 'where', 'while',
    'if', 'unless', 'whether', 'such', 'like', 'for', 'about', 'with', 'from', 'into'
  ]);

  // Common conversational throat-clearing preambles that human editors ruthlessly cut
  private readonly preamblePatterns: string[][] = [
    ['so', 'basically'],
    ['and', 'so'],
    ['i', 'mean'],
    ['you', 'know'],
    ['to', 'be', 'honest'],
    ['honestly'],
    ['well', 'basically'],
    ['like', 'i', 'said'],
    ['so', 'yeah'],
    ['and', 'then'],
    ['so', 'what', 'happened', 'was'],
    ['basically'],
    ['literally'],
    ['you', 'see'],
    ['i', 'think', 'that'],
  ];

  /**
   * Cleans transcript by stripping high-repetition hallucinations commonly generated by Whisper in quiet zones
   */
  public scrubHallucinations(words: Array<{ word: string; start: number; end: number }>): Array<{ word: string; start: number; end: number }> {
    if (words.length < 4) return words;

    const cleaned: Array<{ word: string; start: number; end: number }> = [];
    let repeatCount = 0;
    let lastWord = '';

    for (const item of words) {
      const normalized = item.word.toLowerCase().replace(/[^a-z0-9]/g, '');
      if (normalized === lastWord) {
        repeatCount++;
      } else {
        repeatCount = 1;
        lastWord = normalized;
      }

      // Drop loops of words repeated > 3 times
      if (repeatCount <= 3) {
        cleaned.push(item);
      }
    }

    return cleaned;
  }

  /**
   * Evaluates and adjusts candidate boundaries to ensure complete thoughts, context clarity,
   * sharpened hooks (preamble stripping), and no cliffhangers
   */
  public guardBoundaries(
    allWords: Array<{ word: string; start: number; end: number }>,
    candidateStartSec: number,
    candidateEndSec: number,
    options?: { stripPreamble?: boolean; preRollMs?: number }
  ): GuardedBoundaryResult {
    const shouldStripPreamble = options?.stripPreamble !== false;
    const preRollSec = (options?.preRollMs ?? 0) / 1000;
    let startSec = candidateStartSec;
    let endSec = candidateEndSec;
    let danglingPronounResolved = false;
    let cliffhangerResolved = false;
    let preambleStripped = false;
    let explanation = 'Boundaries are grammatically and contextually complete.';

    const scrubbed = this.scrubHallucinations(allWords);

    // 1. Find the first word in the clip (handling mid-word start cuts)
    let firstWordIndex = scrubbed.findIndex(
      (w) => (w.start <= startSec && w.end > startSec) || w.start >= startSec - 0.15
    );
    if (firstWordIndex !== -1) {
      if (scrubbed[firstWordIndex].start < startSec) {
        // Cut landed mid-word -> snap back to word start
        startSec = Math.max(0, scrubbed[firstWordIndex].start - preRollSec);
      }

      // 1a. Hook Sharpener / Preamble Stripping (Elite Human Editorial Craft)
      // Check if opening words match throat-clearing patterns and advance start to the real punchy hook
      if (shouldStripPreamble) {
        for (const pattern of this.preamblePatterns) {
          const matchesPattern = pattern.every((token, pIdx) => {
            const target = scrubbed[firstWordIndex + pIdx];
            if (!target) return false;
            const clean = target.word.toLowerCase().replace(/[^a-z]/g, '');
            return clean === token;
          });

          if (matchesPattern) {
            const nextIndex = firstWordIndex + pattern.length;
            const cleanStart = nextIndex < scrubbed.length ? Math.max(0, scrubbed[nextIndex].start - preRollSec) : startSec;
            // Ensure we don't overrun past the candidate or truncate below 10 seconds
            if (nextIndex < scrubbed.length && (endSec - cleanStart) >= 10.0) {
              startSec = cleanStart;
              preambleStripped = true;
              firstWordIndex = nextIndex;
              explanation = `Stripped conversational preamble '${pattern.join(' ')}' to start directly on the punchy hook.`;
            }
          }
        }
      }

      // 1b. Check if clip starts with a dangling pronoun
      const firstWord = scrubbed[firstWordIndex]?.word.toLowerCase().replace(/[^a-z]/g, '') || '';
      if (this.danglingPronouns.has(firstWord) && firstWordIndex > 0) {
        // Expand backwards up to 3 words without crossing prior terminal punctuation
        let contextIndex = firstWordIndex;
        for (let i = 1; i <= 3 && (firstWordIndex - i) >= 0; i++) {
          const prevWord = scrubbed[firstWordIndex - i];
          contextIndex = firstWordIndex - i;
          if (/[.?!]$/.test(prevWord.word.trim())) {
            break;
          }
        }
        startSec = Math.max(0, scrubbed[contextIndex].start - preRollSec);
        danglingPronounResolved = true;
        explanation += ` Expanded start backwards to resolve dangling pronoun '${firstWord}'.`;
      }
    }

    // 2. Find the last word in the clip
    let lastWordIndex = -1;
    for (let i = scrubbed.length - 1; i >= 0; i--) {
      if (scrubbed[i].end <= endSec + 0.2) {
        lastWordIndex = i;
        break;
      }
    }
    if (lastWordIndex !== -1) {
      const lastWord = scrubbed[lastWordIndex].word.toLowerCase().replace(/[^a-z]/g, '');

      // Check if clip ends on a trailing conjunction or preposition (cliffhanger)
      if (this.trailingConjunctions.has(lastWord)) {
        if (lastWordIndex < scrubbed.length - 1) {
          // Expand forward to finish the thought and expose incomplete payoff to downstream engines
          endSec = scrubbed[Math.min(scrubbed.length - 1, lastWordIndex + 2)].end;
          cliffhangerResolved = true;
          explanation += ` Expanded end forward to resolve trailing conjunction '${lastWord}'.`;
        } else {
          // Or trim off the dangling conjunction
          endSec = scrubbed[Math.max(0, lastWordIndex - 1)].end;
          cliffhangerResolved = true;
          explanation += ` Trimmed trailing conjunction '${lastWord}' from end.`;
        }
      }
    }

    return {
      startSec: Number(startSec.toFixed(2)),
      endSec: Number(endSec.toFixed(2)),
      danglingPronounResolved,
      cliffhangerResolved,
      preambleStripped,
      hallucinationScrubbed: scrubbed.length !== allWords.length,
      explanation: explanation.trim(),
    };
  }

  /**
   * Evaluates the opening momentum and thesis sharpness of a candidate window.
   * Identifies conversational throat-clearing preambles and suggests thesis start.
   */
  public analyzeOpening(
    allWords: Array<{ word: string; start: number; end: number }>,
    candidateStartSec: number,
    candidateEndSec: number
  ): OpeningAnalysisResult {
    const scrubbed = this.scrubHallucinations(allWords);
    const firstWordIndex = scrubbed.findIndex(
      (w) => (w.start <= candidateStartSec && w.end > candidateStartSec) || w.start >= candidateStartSec - 0.15
    );

    if (firstWordIndex === -1 || scrubbed.length === 0) {
      return {
        hookScore: 50,
        isWeakPreamble: false,
        preambleTokens: [],
        explanation: 'No words found in opening window.',
      };
    }

    // Check for conversational preambles
    for (const pattern of this.preamblePatterns) {
      const matchesPattern = pattern.every((token, pIdx) => {
        const target = scrubbed[firstWordIndex + pIdx];
        if (!target) return false;
        const clean = target.word.toLowerCase().replace(/[^a-z]/g, '');
        return clean === token;
      });

      if (matchesPattern) {
        const nextIndex = firstWordIndex + pattern.length;
        const canAdvance = nextIndex < scrubbed.length && (candidateEndSec - scrubbed[nextIndex].start) >= 10.0;
        return {
          hookScore: 42, // Weak baseline due to throat-clearing fluff
          isWeakPreamble: true,
          thesisStartSec: canAdvance ? scrubbed[nextIndex].start : undefined,
          preambleTokens: pattern,
          explanation: `Opening contains conversational preamble: '${pattern.join(' ')}'.`,
        };
      }
    }

    // Check opening phrasing for hook strength
    const openingWords = scrubbed
      .slice(firstWordIndex, firstWordIndex + 6)
      .map(w => w.word.toLowerCase().replace(/[^a-z0-9]/g, ''));
    const openingText = openingWords.join(' ');

    let hookScore = 70; // Good solid baseline for natural opening
    let explanation = 'Opening starts with clean narrative delivery.';

    // Curiosity & question patterns
    const questionStarters = ['why', 'how', 'what', 'who', 'when', 'where', 'did', 'do', 'can', 'is', 'are'];
    if (questionStarters.includes(openingWords[0])) {
      hookScore += 20;
      explanation = 'Opening launches with an active curiosity question.';
    }

    // Declarative hook / quantitative shock patterns
    const shockPatterns = ['we lost', 'the biggest', 'never', 'always', 'stop', 'the secret', 'nobody knows', 'the truth'];
    if (shockPatterns.some(p => openingText.includes(p))) {
      hookScore += 22;
      explanation = 'Opening delivers an immediate high-impact thesis statement.';
    }

    // Weak filler opening
    const fillerOpeners = ['um', 'uh', 'well', 'okay', 'like'];
    if (fillerOpeners.includes(openingWords[0])) {
      hookScore -= 18;
      explanation = 'Opening begins on a minor filler hesitation.';
    }

    return {
      hookScore: Math.min(100, Math.max(10, hookScore)),
      isWeakPreamble: false,
      preambleTokens: [],
      explanation,
    };
  }
}
