export interface GuardedBoundaryResult {
  startSec: number;
  endSec: number;
  danglingPronounResolved: boolean;
  cliffhangerResolved: boolean;
  hallucinationScrubbed: boolean;
  explanation: string;
}

export class ContextCoherenceGuard {
  private readonly danglingPronouns = new Set([
    'he', 'she', 'it', 'they', 'this', 'that', 'these', 'those', 'his', 'her', 'their', 'its'
  ]);

  private readonly trailingConjunctions = new Set([
    'because', 'and', 'or', 'but', 'which', 'so', 'although', 'though', 'since', 'where', 'while'
  ]);

  /**
   * Cleans transcript by stripping high-repetition hallucinations commonly generated by Whisper in quiet zones
   */
  public scrubHallucinations(words: Array<{ word: string; start: number; end: number }>): Array<{ word: string; start: number; end: number }> {
    if (words.length < 4) return words;

    const cleaned: Array<{ word: string; start: number; end: number }> = [];
    let repeatCount = 0;
    let lastWord = '';

    for (const item of words) {
      const normalized = item.word.toLowerCase().replace(/[^a-z0-9]/g, '');
      if (normalized === lastWord) {
        repeatCount++;
      } else {
        repeatCount = 1;
        lastWord = normalized;
      }

      // Drop loops of words repeated > 3 times
      if (repeatCount <= 3) {
        cleaned.push(item);
      }
    }

    return cleaned;
  }

  /**
   * Evaluates and adjusts candidate boundaries to ensure complete thoughts, context clarity, and no cliffhangers
   */
  public guardBoundaries(
    allWords: Array<{ word: string; start: number; end: number }>,
    candidateStartSec: number,
    candidateEndSec: number
  ): GuardedBoundaryResult {
    let startSec = candidateStartSec;
    let endSec = candidateEndSec;
    let danglingPronounResolved = false;
    let cliffhangerResolved = false;
    let explanation = 'Boundaries are grammatically and contextually complete.';

    const scrubbed = this.scrubHallucinations(allWords);

    // 1. Find the first word in the clip
    const firstWordIndex = scrubbed.findIndex((w) => w.start >= startSec - 0.2);
    if (firstWordIndex !== -1) {
      const firstWord = scrubbed[firstWordIndex].word.toLowerCase().replace(/[^a-z]/g, '');

      // Check if clip starts with a dangling pronoun
      if (this.danglingPronouns.has(firstWord) && firstWordIndex > 0) {
        // Expand backwards up to 3 words to capture the noun/subject context
        const contextIndex = Math.max(0, firstWordIndex - 3);
        startSec = scrubbed[contextIndex].start;
        danglingPronounResolved = true;
        explanation = `Expanded start backwards to resolve dangling pronoun '${firstWord}'.`;
      }
    }

    // 2. Find the last word in the clip
    let lastWordIndex = -1;
    for (let i = scrubbed.length - 1; i >= 0; i--) {
      if (scrubbed[i].end <= endSec + 0.2) {
        lastWordIndex = i;
        break;
      }
    }
    if (lastWordIndex !== -1) {
      const lastWord = scrubbed[lastWordIndex].word.toLowerCase().replace(/[^a-z]/g, '');

      // Check if clip ends on a trailing conjunction (cliffhanger)
      if (this.trailingConjunctions.has(lastWord)) {
        if (lastWordIndex < scrubbed.length - 1) {
          // Expand forward to finish the thought
          endSec = scrubbed[Math.min(scrubbed.length - 1, lastWordIndex + 2)].end;
          cliffhangerResolved = true;
          explanation += ` Expanded end forward to resolve trailing conjunction '${lastWord}'.`;
        } else {
          // Or trim off the dangling conjunction
          endSec = scrubbed[Math.max(0, lastWordIndex - 1)].end;
          cliffhangerResolved = true;
          explanation += ` Trimmed trailing conjunction '${lastWord}' from end.`;
        }
      }
    }

    return {
      startSec: Number(startSec.toFixed(2)),
      endSec: Number(endSec.toFixed(2)),
      danglingPronounResolved,
      cliffhangerResolved,
      hallucinationScrubbed: scrubbed.length !== allWords.length,
      explanation,
    };
  }
}
